#!/bin/bash

curl -X POST  http://localhost:5000/calender/1

curl -X POST -d '{}'  http://localhost:5000/calender/1/task/1

curl -X POST -d '{}'  http://localhost:5000/calender/1/task/2

curl -i GET  http://localhost:5000/calender

curl -X DELETE  http://localhost:5000/calender/1/task/1

curl -i GET  http://localhost:5000/calender
